### 1. Iniciar Sesión para Obtener Token de Admin
@baseUrl = http://localhost:4000

# @name login
POST {{baseUrl}}/api/sesion/login
Content-Type: application/json

{
  "username": "{{$dotenv AUTH_TEST_USERNAME}}",
  "password": "{{$dotenv AUTH_TEST_PASSWORD}}"
}

###

### 2. Consultar Listado de Inventarios (Requiere Rol Admin)
@authToken = {{login.response.body.$.accessToken}}

# @name getAllInventories
GET {{baseUrl}}/api/inventarios
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### 3. Consultar Registro de Inventario por ID (Requiere Rol Admin)

# @name getOneInventory
GET {{baseUrl}}/api/inventarios/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
