### Feature Inventory — CREATE
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name createInventory
POST {{baseUrl}}/api/inventarios
Content-Type: application/json

{
  "branchId": 1,
  "variantId": 1,
  "stock": 50
}
