### Feature Category — DELETE LOGICAL (Desactivar)
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name deactivateCategory
PATCH {{baseUrl}}/api/categorias/1/deactivate
Content-Type: application/json
