### Auth — Obtener Token primero
@baseUrl = http://localhost:4000

# @name login
POST {{baseUrl}}/api/sesion/login
Content-Type: application/json

{
  "username": "{{$dotenv AUTH_TEST_USERNAME}}",
  "password": "{{$dotenv AUTH_TEST_PASSWORD}}"
}

###

### Feature Client — READ ALL (CON AUTH)
@authToken = {{login.response.body.$.accessToken}}

# @name getAllClients
GET {{baseUrl}}/api/clientes
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Feature Client — READ ONE (CON AUTH)

# @name getOneClient
GET {{baseUrl}}/api/clientes/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
