### Login with the configured authentication test account
@baseUrl = http://localhost:4000
@username = {{$dotenv AUTH_TEST_USERNAME}}
@password = {{$dotenv AUTH_TEST_PASSWORD}}

# @name login
POST {{baseUrl}}/api/sesion/login
Content-Type: application/json
Accept: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

### Verify the access token and get the authenticated profile
@authToken = {{login.response.body.$.accessToken}}

GET {{baseUrl}}/api/sesion/me
Authorization: Bearer {{authToken}}
Accept: application/json
