### Feature Collection — CREATE
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name createCollection
POST {{baseUrl}}/api/colecciones
Content-Type: application/json

{
  "nombre": "Primavera - Verano 2026",
  "descripcion": "Colección de prendas ligeras, linos y tonos pasteles"
}
