### Feature Branch — READ ALL
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name getAllBranches
GET {{baseUrl}}/api/sucursales
Content-Type: application/json

###

### Feature Branch — READ ONE
### Leyenda: SIN AUTH

# @name getOneBranch
GET {{baseUrl}}/api/sucursales/1
Content-Type: application/json
