### Feature Supplier — CREATE
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name createSupplier
POST {{baseUrl}}/api/proveedores
Content-Type: application/json

{
  "name": "Textiles del Norte S.A.",
  "contact_name": "Carlos Gómez",
  "email": "contacto@textilesnorte.com",
  "phone": "+573001234567",
  "address": "Calle 45 # 12-34, Medellín"
}
