### Feature Supplier — READ ALL
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name getAllSuppliers
GET {{baseUrl}}/api/proveedores
Content-Type: application/json

###

### Feature Supplier — READ ONE
### Leyenda: SIN AUTH

# @name getOneSupplier
GET {{baseUrl}}/api/proveedores/1
Content-Type: application/json
