### 1. Iniciar Sesión para Obtener Token (Ejecutar primero)
@baseUrl = http://localhost:4000

# @name login
POST {{baseUrl}}/api/sesion/login
Content-Type: application/json

{
  "username": "{{$dotenv AUTH_TEST_USERNAME}}",
  "password": "{{$dotenv AUTH_TEST_PASSWORD}}"
}

###

### 2. Registrar una Nueva Venta (Requiere Auth)
@authToken = {{login.response.body.$.accessToken}}

# @name createSale
POST {{baseUrl}}/api/ventas
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "clientId": 1,
  "branchId": 1,
  "total": 150000
}
