### Feature Variant — UPDATE
### Leyenda: SIN AUTH
@baseUrl = http://localhost:4000

# @name updateVariant
PUT {{baseUrl}}/api/variantes/1
Content-Type: application/json

{
  "nombre": "Talla L - Color Azul Marino",
  "descripcion": "Variante física actualizada a Talla L"
}
