### 1. Iniciar Sesión para Obtener Token de Admin
@baseUrl = http://localhost:4000

# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@tramamoda.com",
  "password": "AdminPassword123!"
}

###

### 2. Consultar Listado de Usuarios (Requiere Rol Admin)
@authToken = {{login.response.body.token}}

GET {{baseUrl}}/api/usuarios
Authorization: Bearer {{authToken}}
Content-Type: application/json
